#!/bin/bash
[ ! $(which ffplay) ] && { echo ffplay is necessary to run this. Maybe you can install it with: 'brew install --with-ffplay --with-freetext ffmpeg'; exit 1 ;};

usage(){
    echo "
    $(basename $0)

    usage: $(basename $0) [ filteroption ] [ -o outputfile ] inputfile

    use - (hyphen) for the input if it is a pipe (for instace: bmdcapture -v -F nut -c 2 -s 16 -p 8 -m 0 -f pipe:1 | analyzeplay -c -)

    filter options:
    -f        split field mode
    -d        field difference mode. midtone gray means no difference in between fields
    -c        channel split mode
    -w        field waveform mode, waveforms per channel per field (depreciated and inaccurate)
    -r        field waveform mode with highlights for broadcast range (depreciated and inaccurate)
    -R        waveform in parade mode
    -H        field histogram mode, histograms per field
    -v        field vectrscope mode, vectroscopes per field
    -i        highlight interlacement artifacts
    -l        field histogram mode, histograms per field
    -b        bit slice playback per field, enter 1 through 8 to show that bit value (only supports the most significant 8 bits)
    -A        field waveform mode with highlights for broadcast range (draft #2)
    -B        field waveform mode with highlights for broadcast range on field 1 only
    -C        field waveform mode with highlights for broadcast range on field 2 only
    -D        field waveform mode with highlights for broadcast range showing field 1 on top and field 2 on bottom
    -E        highlight pixels that are outside of broadcast range
    -F        highlight pixels that are outside of broadcast range showing field 1 on top and field 2 on bottom

    optional output:
    -o        outputfile

    "
}

# filter recipes
fieldsplitplay="-vf 'split[a][b]; [a]pad=iw:ih*2,field=top[src]; [b]field=bottom[filt]; [src][filt]overlay=0:h'"
fielddiffplay="-vf 'split=4[a][b][c][d]; [a]pad=iw:ih*3,field=top[src]; [b]field=bottom[filt];[c]field=bottom[bb];[d]field=top,negate[tb];[src][filt]overlay=0:h[upper];[bb][tb]blend=all_mode=average[blend];[upper][blend]overlay=0:h*2'"
fieldwaveformplay="-vf 'split[a][b];[a]field=top,split[topa][topb];[b]field=bottom,split[bota][botb];[topb]histogram=mode=waveform:waveform_mode=column:waveform_mirror=1[topbh];[botb]histogram=mode=waveform:waveform_mode=column:waveform_mirror=1[botbh];[topa]pad=iw*2:ih+(256*3)[topapad];[topapad][bota]overlay=w[rowa];[rowa][topbh]overlay=0:H-(256*3)[rowab1];[rowab1][botbh]overlay=w:H-(256*3)'"
rangewaveformplay="-vf 'split[a][b];[a]format=gray,histogram=mode=waveform:waveform_mode=column:waveform_mirror=1,split[c][d];[b]pad=iw:ih+256[padded];[c]geq=g=1:b=1[red];[d]geq=r=1:b=1,crop=in_w:220:0:16[mid];[red][mid]overlay=0:16[wave];[padded][wave]overlay=0:H-h'"
waveformplayparade="-vf 'split[a][b];[a]histogram=mode=waveform:waveform_mode=column:waveform_mirror=1:display_mode=overlay[c];[b]pad=iw:ih+256[padded];[padded][c]overlay=0:H-h'"
fieldhistogramplay="-vf 'split[a][b];[a]field=top,split[topa][topb];[b]field=bottom,split[bota][botb];[topb]histogram[topbh];[botb]histogram[botbh];[topa]pad=iw*2:ih+636[topapad];[topapad][bota]overlay=w[rowa];[rowa][topbh]overlay=W/2-256:H-636[rowab1];[rowab1][botbh]overlay=W/2:H-636'"
fieldvectroscopeplay="-vf 'split[a][b];[a]field=top,split[topa][topb];[b]field=bottom,split[bota][botb];[topb]histogram=mode=color[topbh];[botb]histogram=mode=color[botbh];[topa]pad=iw*2:ih+256[topapad];[topapad][bota]overlay=w[rowa];[rowa][topbh]overlay=W/2-256:H-256[rowab1];[rowab1][botbh]overlay=W/2:H-256'"
chromasplitplay="-vf 'split=4[a][b][c][d];[a]pad=iw*2:ih*2[w];[b]lutyuv=u=128:v=128[x];[c]lutyuv=y=128:v=128,curves=strong_contrast[y];[d]lutyuv=y=128:u=128,curves=strong_contrast[z];[w][x]overlay=w:0[wx];[wx][y]overlay=0:h[wxy];[wxy][z]overlay=w:h'"
interlaceplay="-vf 'kerndeint=map=1'"

# Name: Waveform
# Description: A waveform display. Guide lines are drawn at 7.5 IRE (0x16) and 100 IRE (0xEB). The area above 100 IRE is tinted in crimson and below 7.5 IRE is tinted aqua. These ranges, above 100 IRE and below 7.5 IRE, show luminosity values outside of broadcast range.
FILTER_WAVEFORM="-vf 'histogram=step=16:mode=waveform:waveform_mode=column:waveform_mirror=1,crop=iw:256:0:0,drawgrid=y=(256-16):c=white@0.4,drawgrid=y=(256-235):c=white@0.4,drawbox=y=(256-16):w=iw:h=16:color=aqua@0.2:t=16,drawbox=w=iw:h=(256-235):color=crimson@0.2:t=16,scale=720x486'"
# Name: Waveform (Field 1 Only)
FILTER_WAVEFORM_F1="-vf 'field=top,histogram=step=16:mode=waveform:waveform_mode=column:waveform_mirror=1,crop=iw:256:0:0,drawgrid=y=(256-16):c=white@0.4,drawgrid=y=(256-235):c=white@0.4,drawbox=y=(256-16):w=iw:h=16:color=aqua@0.2:t=16,drawbox=w=iw:h=(256-235):color=crimson@0.2:t=16,scale=720x486'"
# Name: Waveform (Field 2 Only)
FILTER_WAVEFORM_F2="-vf 'field=bottom,histogram=step=16:mode=waveform:waveform_mode=column:waveform_mirror=1,crop=iw:256:0:0,drawgrid=y=(256-16):c=white@0.4,drawgrid=y=(256-235):c=white@0.4,drawbox=y=(256-16):w=iw:h=16:color=aqua@0.2:t=16,drawbox=w=iw:h=(256-235):color=crimson@0.2:t=16,scale=720x486'"
# Name: Waveform (field-split)
FILTER_WAVEFORM_FS="-vf 'split[a][b];[a]field=top[c];[b]field=bottom[d];[c]histogram=step=16:mode=waveform:waveform_mode=column:waveform_mirror=1,crop=iw:256:0:0,drawgrid=y=(256-16):c=white@0.4,drawgrid=y=(256-235):c=white@0.4,drawbox=y=(256-16):w=iw:h=16:color=aqua@0.2:t=16,drawbox=w=iw:h=(256-235):color=crimson@0.2:t=16[e];[d]histogram=step=16:mode=waveform:waveform_mode=column:waveform_mirror=1,crop=iw:256:0:0,drawgrid=y=(256-16):c=white@0.4,drawgrid=y=(256-235):c=white@0.4,drawbox=y=(256-16):w=iw:h=16:color=aqua@0.2:t=16,drawbox=w=iw:h=(256-235):color=crimson@0.2:t=16[f];[e]pad=0:ih*2[g];[g][f]overlay=0:h'"
# Name: Broadcast Range Pixels
# Description: All pixels from 0 to 7.5 IRE and 100-110 IRE will be highlighted as white pixels to illuminate what area(s) of the frame and how many pixels are outside of braodcast range
FILTER_RANG="-vf 'values=out=rang'"
# Name: Broadcast Range (field-split)
FILTER_RANG_FS="-vf 'split[a][b];[a]field=top[c];[b]field=bottom[d];[c]values=out=rang[e];[d]values=out=rang[f];[e]pad=0:ih*2[g];[g][f]overlay=0:h'"


[ "$#" = 0 ] && { usage ; exit 1 ;};
while getopts fcdwrRHvib:ABCDEFo:h opt ; do
    case "$opt" in
        f) filter="$fieldsplitplay" ;;
        d) filter="$fielddiffplay" ;;
        c) filter="$chromasplitplay" ;;
        w) filter="$fieldwaveformplay" ;;
        r) filter="$rangewaveformplay" ;;
        R) filter="$waveformplayparade" ;;
        H) filter="$fieldhistogramplay" ;;
        v) filter="$fieldvectroscopeplay" ;;
        i) filter="$interlaceplay" ;;
        b)
            bit="$OPTARG"
            [[ "$bit" == [1-8] ]] || { echo The bit value must be between 1 and 8 ; exit 1 ;}; 
            bitand=$(echo "2^(8-$bit)" | bc)
            times=$(echo "2^$bit" | bc)
            echo "bit $bit"
            filter="-vf 'split[a][b]; [a]pad=iw:ih*2,field=top,lutyuv=y=bitand(val\, $bitand)*$times:u=128:v=128[src]; [b]field=bottom,lutyuv=y=bitand(val\, $bitand)*$times:u=128:v=128[filt];[src][filt]overlay=0:h'";;
        A) filter="$FILTER_WAVEFORM" ;;
        B) filter="$FILTER_WAVEFORM_F1" ;;
        C) filter="$FILTER_WAVEFORM_F2" ;;
        D) filter="$FILTER_WAVEFORM_FS" ;;
        E) filter="$FILTER_RANG" ;;
        F) filter="$FILTER_RANG_FS" ;;
        o) outputfile="$OPTARG" ;;
        h) usage ; exit 1 ;;
        \?) usage ; exit 1 ;;
    esac
done
shift $(( ${OPTIND} - 1 ))
inputfile="$1"
[ ! -f "$inputfile" ] && [ ! "$inputfile" = "-" ] && { echo No input file detected. ; usage ; exit 1 ;};
[ -n "$outputfile" ] && command="ffmpeg -i \"$inputfile\" $filter \"$outputfile\"" || command="ffplay \"$inputfile\" $filter"
echo "Running: $command"
eval "$command"
