#!/bin/bash
[ ! $(which ffplay) ] && { echo ffplay is necessary to run this. Maybe you can install it with: 'brew install --with-ffplay --with-freetext ffmpeg'; exit 1 ;};

usage(){
	echo "
	$(basename $0)

	usage: $(basename $0) [ filteroption ] [ -o outputfile ] inputfile

	filter options:
	-f		split field mode
	-c		channel split mode
	-d		field difference mode. midtone gray means no difference in between fields
	-w		field waveform mode, waveforms per channel per field
	-v		field vectrscope mode, vectroscopes per field
	-l		field histogram mode, histograms per field
	-b		bit slice playback per field, enter 1 through 8 to show that bit value (only supports the most significant 8 bits)
	-i		highlight interlacement artifacts

	optional output:
	-o		outputfile

	"
}

# filter recipes
fieldsplitplay="-vf 'split[a][b]; [a]pad=iw:ih*2,field=top[src]; [b]field=bottom[filt]; [src][filt]overlay=0:h'"
fielddiffplay="-vf 'split=4[a][b][c][d]; [a]pad=iw:ih*3,field=top[src]; [b]field=bottom[filt];[c]field=bottom[bb];[d]field=top,negate[tb];[src][filt]overlay=0:h[upper];[bb][tb]blend=all_mode=average[blend];[upper][blend]overlay=0:h*2'"
fieldwaveformplay="-vf 'split[a][b];[a]field=top,split[topa][topb];[b]field=bottom,split[bota][botb];[topb]histogram=mode=waveform:waveform_mode=column:waveform_mirror=1[topbh];[botb]histogram=mode=waveform:waveform_mode=column:waveform_mirror=1[botbh];[topa]pad=iw*2:ih+(256*3)[topapad];[topapad][bota]overlay=w[rowa];[rowa][topbh]overlay=0:H-(256*3)[rowab1];[rowab1][botbh]overlay=w:H-(256*3)'"
rangewaveformplay="-vf 'split[a][b];[a]format=gray,histogram=mode=waveform:waveform_mode=column:waveform_mirror=1,split[c][d];[b]pad=iw:ih+256[padded];[c]geq=g=1:b=1[red];[d]geq=r=1:b=1,crop=in_w:220:0:16[mid];[red][mid]overlay=0:16[wave];[padded][wave]overlay=0:H-h'"
waveformplayparade="-vf 'split[a][b];[a]histogram=mode=waveform:waveform_mode=column:waveform_mirror=1:display_mode=overlay[c];[b]pad=iw:ih+256[padded];[padded][c]overlay=0:H-h'"
fieldhistogramplay="-vf 'split[a][b];[a]field=top,split[topa][topb];[b]field=bottom,split[bota][botb];[topb]histogram[topbh];[botb]histogram[botbh];[topa]pad=iw*2:ih+636[topapad];[topapad][bota]overlay=w[rowa];[rowa][topbh]overlay=W/2-256:H-636[rowab1];[rowab1][botbh]overlay=W/2:H-636'"
fieldvectroscopeplay="-vf 'split=4[a][b][c][d]; [a]pad=iw*2:ih*3,field=top[top]; [b]field=bottom[bot]; [top][bot]overlay=w[rowa];[c]field=top,histogram=mode=color,pad=iw*2[rowba];[d]field=bottom,histogram=mode=color[rowbb];[rowba][rowbb]overlay=w[rowb];[rowa][rowb]overlay=0:h'"
chromasplitplay="-vf 'split=4[a][b][c][d];[a]pad=iw*2:ih*2[w];[b]lutyuv=u=128:v=128[x];[c]lutyuv=y=128:v=128,curves=strong_contrast[y];[d]lutyuv=y=128:u=128,curves=strong_contrast[z];[w][x]overlay=w:0[wx];[wx][y]overlay=0:h[wxy];[wxy][z]overlay=w:h'"
interlaceplay="-vf 'kerndeint=map=1'"

[ "$#" = 0 ] && { usage ; exit 1 ;};
while getopts fcdwrRHvilb:o:h opt ; do
	case "$opt" in
		f) filter="$fieldsplitplay" ;;
		d) filter="$fielddiffplay" ;;
		c) filter="$chromasplitplay" ;;
		w) filter="$fieldwaveformplay" ;;
		r) filter="$rangewaveformplay" ;;
		R) filter="$waveformplayparade" ;;
		H) filter="$fieldhistogramplay" ;;
		v) filter="$fieldvectroscopeplay" ;;
		i) filter="$interlaceplay" ;;
		l) filter="$fieldhistogramplay" ;;
		b)
			bit="$OPTARG"
			[[ "$bit" == [1-8] ]] || { echo The bit value must be between 1 and 8 ; exit 1 ;}; 
			bitand=$(echo "2^(8-$bit)" | bc)
			times=$(echo "2^$bit" | bc)
			echo "bit $bit"
			filter="-vf 'split[a][b]; [a]pad=iw:ih*2,field=top,lutyuv=y=bitand(val\, $bitand)*$times:u=128:v=128[src]; [b]field=bottom,lutyuv=y=bitand(val\, $bitand)*$times:u=128:v=128[filt];[src][filt]overlay=0:h'";;
		o) outputfile="$OPTARG" ;;
		h) usage ; exit 1 ;;
		\?) usage ; exit 1 ;;
	esac
done
shift $(( ${OPTIND} - 1 ))
inputfile="$1"
[ ! -f "$inputfile" ] && { echo No input file detected. ; usage ; exit 1 ;};
[ -n "$outputfile" ] && command="ffmpeg -i \"$inputfile\" $filter \"$outputfile\"" || command="ffplay \"$inputfile\" $filter"
echo "Running: $command"
eval "$command"
